# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  annotations:
    # Keep the shared claim when application trees are pruned.
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-media
  volumeName: media
  resources:
    requests:
      storage: 1Ti
